# Generated by Django 3.1.2 on 2020-10-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
