# Generated by Django 3.1.2 on 2020-10-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0004_auto_20201026_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rate_usage',
            new_name='rate_usability',
        ),
    ]
