# Generated by Django 3.1.2 on 2020-10-24 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Bio',
            new_name='bio',
        ),
    ]
